all: Joseph SetOperate ParkManage DevilLang Huffman
.PHONY: all
Joseph: Joseph.c 
	gcc -o Joseph Joseph.c
SetOperate: SetOperate.c
	gcc -o SetOperate SetOperate.c
ParkManage: ParkManage.c
	gcc -o ParkManage ParkManage.c
DevilLang: DevilLang.c
	gcc -o DevilLang DevilLang.c
Huffman: Huffman.cc
	g++ -std=c++0x -g -o Huffman Huffman.cc
clean:
	rm Joseph SetOperate ParkManage DevilLang Huffman
